### ISSUE TITLE
Many errors in logs

### ISSUE THREAD

**Issue by Reshy** [BlueDuckYT/DustrialDecor#16]
Getting some errors with the mod, this is one such instance but it also happens with the following blocks:

[07:46:59] [Render thread/ERROR]: Couldn't parse loot table dustrial_decor:blocks/large_ender_lantern
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'dustrial_decor:large_ender_lantern'
[07:47:02] [Render thread/ERROR]: Couldn't parse loot table dustrial_decor:blocks/large_ice_chain
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'dustrial_decor:large_ice_chain'
[07:47:04] [Render thread/ERROR]: Couldn't parse loot table dustrial_decor:blocks/sheet_metal_paneling_vertical_slab
java.lang.IllegalArgumentException: Can't find block dustrial_decor:sheet_metal_paneling_vertical_slab
[07:47:05] [Render thread/ERROR]: Couldn't parse loot table dustrial_decor:blocks/large_glow_lantern
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'dustrial_decor:large_glow_lantern'

[07:46:58] [Render thread/ERROR]: Couldn't parse loot table dustrial_decor:blocks/wrapped_ice_chains
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'dustrial_decor:wrapped_ice_chains'
at net.minecraft.util.GsonHelper.m_13866_(GsonHelper.java:130) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
at net.minecraft.util.GsonHelper.m_13874_(GsonHelper.java:130) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.util.GsonHelper.m_13909_(GsonHelper.java:138) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.world.level.storage.loot.entries.LootItem$Serializer.m_7267_(LootItem.java:55) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.world.level.storage.loot.entries.LootItem$Serializer.m_7267_(LootItem.java:40) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_5921_(LootPoolSingletonContainer.java:151) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_5921_(LootPoolSingletonContainer.java:129) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_7561_(LootPoolEntryContainer.java:86) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_7561_(LootPoolEntryContainer.java:74) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.deserialize(GsonAdapterFactory.java:102) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.9.jar%2334!/:?]
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.9.jar%2334!/:?]
at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.9.jar%2334!/:?]
at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar%2334!/:?]
at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.8.9.jar%2334!/:?]
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.9.jar%2334!/:?]
at net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:448) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.util.GsonHelper.m_13836_(GsonHelper.java:456) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.world.level.storage.loot.LootPool$Serializer.deserialize(LootPool.java:190) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.world.level.storage.loot.LootPool$Serializer.deserialize(LootPool.java:187) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.9.jar%2334!/:?]
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.9.jar%2334!/:?]
at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.9.jar%2334!/:?]
at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar%2334!/:?]
at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.8.9.jar%2334!/:?]
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.9.jar%2334!/:?]
at net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:448) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.util.GsonHelper.m_13845_(GsonHelper.java:466) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.world.level.storage.loot.LootTable$Serializer.deserialize(LootTable.java:255) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.world.level.storage.loot.LootTable$Serializer.deserialize(LootTable.java:252) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.9.jar%2334!/:?]
at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar%2334!/:?]
at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.8.9.jar%2334!/:?]
at com.google.gson.Gson.fromJson(Gson.java:1006) ~[gson-2.8.9.jar%2334!/:?]
at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:814) ~[forge-1.18.2-40.1.0-universal.jar%23265!/:?]
at net.minecraft.world.level.storage.loot.LootTables.lambda$apply$0(LootTables.java:41) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
at net.minecraft.world.level.storage.loot.LootTables.m_5787_(LootTables.java:39) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.world.level.storage.loot.LootTables.m_5787_(LootTables.java:17) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.client.Minecraft.m_205125_(Minecraft.java:2075) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.client.Minecraft.doLoadLevel(Minecraft.java:1902) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.client.Minecraft.m_205185_(Minecraft.java:1870) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.m_100972_(CreateWorldScreen.java:246) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.lambda$init$13(CreateWorldScreen.java:195) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.client.gui.components.Button.m_5691_(Button.java:40) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.client.gui.components.AbstractButton.m_5716_(AbstractButton.java:16) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:111) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:88) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:528) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81) ~[lwjgl-glfw-3.2.2.jar%2347!/:build 10]
at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:133) ~[FpsReducer2-forge-1.18.2-2.0.jar%23144!/:1.18.2-2.0]
at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar%2347!/:build 10]
at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar%2343!/:build 10]
at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar%2347!/:build 10]
at com.mojang.blaze3d.systems.RenderSystem.handler$zjd000$handleWaitEventsTimeout(RenderSystem.java:1990) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at com.mojang.blaze3d.systems.RenderSystem.m_69830_(RenderSystem.java) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1069) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.0.jar%2316!/:?]
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]

[07:47:02] [Render thread/ERROR]: Couldn't parse loot table dustrial_decor:blocks/rusty_sheet_metal_paneling_vertical_slab
java.lang.IllegalArgumentException: Can't find block dustrial_decor:rusty_sheet_metal_paneling_vertical_slab
	at net.minecraft.world.level.storage.loot.predicates.LootItemBlockStatePropertyCondition$Serializer.m_81802_(LootItemBlockStatePropertyCondition.java:79) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.world.level.storage.loot.predicates.LootItemBlockStatePropertyCondition$Serializer.m_7561_(LootItemBlockStatePropertyCondition.java:79) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.world.level.storage.loot.predicates.LootItemBlockStatePropertyCondition$Serializer.m_7561_(LootItemBlockStatePropertyCondition.java:68) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.deserialize(GsonAdapterFactory.java:102) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.9.jar%2334!/:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.9.jar%2334!/:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.9.jar%2334!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar%2334!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.8.9.jar%2334!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.9.jar%2334!/:?]
	at net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:448) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.util.GsonHelper.m_13845_(GsonHelper.java:466) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.world.level.storage.loot.functions.LootItemConditionalFunction$Serializer.m_7561_(LootItemConditionalFunction.java:98) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.world.level.storage.loot.functions.LootItemConditionalFunction$Serializer.m_7561_(LootItemConditionalFunction.java:88) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.deserialize(GsonAdapterFactory.java:102) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.9.jar%2334!/:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.9.jar%2334!/:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.9.jar%2334!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar%2334!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.8.9.jar%2334!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.9.jar%2334!/:?]
	at net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:448) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.util.GsonHelper.m_13845_(GsonHelper.java:466) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_5921_(LootPoolSingletonContainer.java:149) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_5921_(LootPoolSingletonContainer.java:129) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_7561_(LootPoolEntryContainer.java:86) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_7561_(LootPoolEntryContainer.java:74) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.deserialize(GsonAdapterFactory.java:102) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.9.jar%2334!/:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.9.jar%2334!/:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.9.jar%2334!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar%2334!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.8.9.jar%2334!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.9.jar%2334!/:?]
	at net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:448) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.util.GsonHelper.m_13836_(GsonHelper.java:456) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.world.level.storage.loot.LootPool$Serializer.deserialize(LootPool.java:190) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.world.level.storage.loot.LootPool$Serializer.deserialize(LootPool.java:187) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.9.jar%2334!/:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.9.jar%2334!/:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.9.jar%2334!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar%2334!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.8.9.jar%2334!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.9.jar%2334!/:?]
	at net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:448) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.util.GsonHelper.m_13845_(GsonHelper.java:466) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.world.level.storage.loot.LootTable$Serializer.deserialize(LootTable.java:255) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.world.level.storage.loot.LootTable$Serializer.deserialize(LootTable.java:252) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.9.jar%2334!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar%2334!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.8.9.jar%2334!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:1006) ~[gson-2.8.9.jar%2334!/:?]
	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:814) ~[forge-1.18.2-40.1.0-universal.jar%23265!/:?]
	at net.minecraft.world.level.storage.loot.LootTables.lambda$apply$0(LootTables.java:41) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at net.minecraft.world.level.storage.loot.LootTables.m_5787_(LootTables.java:39) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.world.level.storage.loot.LootTables.m_5787_(LootTables.java:17) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.client.Minecraft.m_205125_(Minecraft.java:2075) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.client.Minecraft.doLoadLevel(Minecraft.java:1902) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.client.Minecraft.m_205185_(Minecraft.java:1870) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.m_100972_(CreateWorldScreen.java:246) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.lambda$init$13(CreateWorldScreen.java:195) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.client.gui.components.Button.m_5691_(Button.java:40) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.client.gui.components.AbstractButton.m_5716_(AbstractButton.java:16) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:111) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:88) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:528) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81) ~[lwjgl-glfw-3.2.2.jar%2347!/:build 10]
	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:133) ~[FpsReducer2-forge-1.18.2-2.0.jar%23144!/:1.18.2-2.0]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar%2347!/:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar%2343!/:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar%2347!/:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.handler$zjd000$handleWaitEventsTimeout(RenderSystem.java:1990) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at com.mojang.blaze3d.systems.RenderSystem.m_69830_(RenderSystem.java) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1069) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23261!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.0.jar%2316!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]

**Comment by TheRealBrobie** [comment]
I am having similar issues. Looks like unfinished content added to the mod from what I can tell, but I'm not versed in java well enough to know how to fix it.

**Comment by UnRealDinnerbone** [comment]
Any update on fixing this?

**Comment by Darky49** [comment]
duplicate of #10
